//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVRActionVector2 p_default_Move;
        
        private static SteamVRActionBoolean p_default_Grab;
        
        private static SteamVRActionPose p_default_Pose;
        
        private static SteamVRActionSkeleton p_default_SkeletonLeftHand;
        
        private static SteamVRActionSkeleton p_default_SkeletonRightHand;
        
        private static SteamVRActionBoolean p_default_HeadsetOnHead;
        
        private static SteamVRActionBoolean p_default_SnapTurnLeft;
        
        private static SteamVRActionBoolean p_default_SnapTurnRight;
        
        private static SteamVRActionBoolean p_default_UI_Radial;
        
        private static SteamVRActionBoolean p_default_Self_Radial;
        
        private static SteamVRActionBoolean p_default_Pee;
        
        private static SteamVRActionBoolean p_default_Masturbate;
        
        private static SteamVRActionBoolean p_default_InteractUI;
        
        private static SteamVRActionBoolean p_default_Inventory;
        
        private static SteamVRActionBoolean p_default_Memories;
        
        private static SteamVRActionBoolean p_default_Opportunities;
        
        private static SteamVRActionBoolean p_default_Flash;
        
        private static SteamVRActionBoolean p_default_GameMenu;
        
        private static SteamVRActionBoolean p_default_Combat;
        
        private static SteamVRActionBoolean p_default_Crouch;
        
        private static SteamVRActionVibration p_default_Haptic;
        
        public static SteamVRActionVector2 default_Move
        {
            get
            {
                return SteamVR_Actions.p_default_Move.GetCopy<SteamVRActionVector2>();
            }
        }
        
        public static SteamVRActionBoolean default_Grab
        {
            get
            {
                return SteamVR_Actions.p_default_Grab.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionPose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVRActionPose>();
            }
        }
        
        public static SteamVRActionSkeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVRActionSkeleton>();
            }
        }
        
        public static SteamVRActionSkeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVRActionSkeleton>();
            }
        }
        
        public static SteamVRActionBoolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnLeft.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnRight.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_UI_Radial
        {
            get
            {
                return SteamVR_Actions.p_default_UI_Radial.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Self_Radial
        {
            get
            {
                return SteamVR_Actions.p_default_Self_Radial.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Pee
        {
            get
            {
                return SteamVR_Actions.p_default_Pee.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Masturbate
        {
            get
            {
                return SteamVR_Actions.p_default_Masturbate.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Inventory
        {
            get
            {
                return SteamVR_Actions.p_default_Inventory.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Memories
        {
            get
            {
                return SteamVR_Actions.p_default_Memories.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Opportunities
        {
            get
            {
                return SteamVR_Actions.p_default_Opportunities.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Flash
        {
            get
            {
                return SteamVR_Actions.p_default_Flash.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_GameMenu
        {
            get
            {
                return SteamVR_Actions.p_default_GameMenu.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Combat
        {
            get
            {
                return SteamVR_Actions.p_default_Combat.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionBoolean default_Crouch
        {
            get
            {
                return SteamVR_Actions.p_default_Crouch.GetCopy<SteamVRActionBoolean>();
            }
        }
        
        public static SteamVRActionVibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVRActionVibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVRInput.actions = new Valve.VR.SteamVRAction[] {
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_Grab,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_UI_Radial,
                    SteamVR_Actions.default_Self_Radial,
                    SteamVR_Actions.default_Pee,
                    SteamVR_Actions.default_Masturbate,
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Inventory,
                    SteamVR_Actions.default_Memories,
                    SteamVR_Actions.default_Opportunities,
                    SteamVR_Actions.default_Flash,
                    SteamVR_Actions.default_GameMenu,
                    SteamVR_Actions.default_Combat,
                    SteamVR_Actions.default_Crouch,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVRInput.actionsIn = new Valve.VR.ISteamVRActionIn[] {
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_Grab,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_UI_Radial,
                    SteamVR_Actions.default_Self_Radial,
                    SteamVR_Actions.default_Pee,
                    SteamVR_Actions.default_Masturbate,
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Inventory,
                    SteamVR_Actions.default_Memories,
                    SteamVR_Actions.default_Opportunities,
                    SteamVR_Actions.default_Flash,
                    SteamVR_Actions.default_GameMenu,
                    SteamVR_Actions.default_Combat,
                    SteamVR_Actions.default_Crouch};
            Valve.VR.SteamVRInput.actionsOut = new Valve.VR.ISteamVRActionOut[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVRInput.actionsVibration = new Valve.VR.SteamVRActionVibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVRInput.actionsPose = new Valve.VR.SteamVRActionPose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVRInput.actionsBoolean = new Valve.VR.SteamVRActionBoolean[] {
                    SteamVR_Actions.default_Grab,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_UI_Radial,
                    SteamVR_Actions.default_Self_Radial,
                    SteamVR_Actions.default_Pee,
                    SteamVR_Actions.default_Masturbate,
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Inventory,
                    SteamVR_Actions.default_Memories,
                    SteamVR_Actions.default_Opportunities,
                    SteamVR_Actions.default_Flash,
                    SteamVR_Actions.default_GameMenu,
                    SteamVR_Actions.default_Combat,
                    SteamVR_Actions.default_Crouch};
            Valve.VR.SteamVRInput.actionsSingle = new Valve.VR.SteamVRActionSingle[0];
            Valve.VR.SteamVRInput.actionsVector2 = new Valve.VR.SteamVRActionVector2[] {
                    SteamVR_Actions.default_Move};
            Valve.VR.SteamVRInput.actionsVector3 = new Valve.VR.SteamVRActionVector3[0];
            Valve.VR.SteamVRInput.actionsSkeleton = new Valve.VR.SteamVRActionSkeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVRInput.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVRActionIn[] {
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_Grab,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_UI_Radial,
                    SteamVR_Actions.default_Self_Radial,
                    SteamVR_Actions.default_Pee,
                    SteamVR_Actions.default_Masturbate,
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Inventory,
                    SteamVR_Actions.default_Memories,
                    SteamVR_Actions.default_Opportunities,
                    SteamVR_Actions.default_Flash,
                    SteamVR_Actions.default_GameMenu,
                    SteamVR_Actions.default_Combat,
                    SteamVR_Actions.default_Crouch};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Move = ((SteamVRActionVector2)(SteamVRAction.Create<SteamVRActionVector2>("/actions/default/in/Move")));
            SteamVR_Actions.p_default_Grab = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Grab")));
            SteamVR_Actions.p_default_Pose = ((SteamVRActionPose)(SteamVRAction.Create<SteamVRActionPose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVRActionSkeleton)(SteamVRAction.Create<SteamVRActionSkeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVRActionSkeleton)(SteamVRAction.Create<SteamVRActionSkeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_SnapTurnLeft = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/SnapTurnLeft")));
            SteamVR_Actions.p_default_SnapTurnRight = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/SnapTurnRight")));
            SteamVR_Actions.p_default_UI_Radial = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/UI Radial")));
            SteamVR_Actions.p_default_Self_Radial = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Self_Radial")));
            SteamVR_Actions.p_default_Pee = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Pee")));
            SteamVR_Actions.p_default_Masturbate = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Masturbate")));
            SteamVR_Actions.p_default_InteractUI = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Inventory = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Inventory")));
            SteamVR_Actions.p_default_Memories = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Memories")));
            SteamVR_Actions.p_default_Opportunities = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Opportunities")));
            SteamVR_Actions.p_default_Flash = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Flash")));
            SteamVR_Actions.p_default_GameMenu = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/GameMenu")));
            SteamVR_Actions.p_default_Combat = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Combat")));
            SteamVR_Actions.p_default_Crouch = ((SteamVRActionBoolean)(SteamVRAction.Create<SteamVRActionBoolean>("/actions/default/in/Crouch")));
            SteamVR_Actions.p_default_Haptic = ((SteamVRActionVibration)(SteamVRAction.Create<SteamVRActionVibration>("/actions/default/out/Haptic")));
        }
    }
}
