//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.default_Grab;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean UI_Radial
        {
            get
            {
                return SteamVR_Actions.default_UI_Radial;
            }
        }
        
        public virtual SteamVR_Action_Boolean Self_Radial
        {
            get
            {
                return SteamVR_Actions.default_Self_Radial;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pee
        {
            get
            {
                return SteamVR_Actions.default_Pee;
            }
        }
        
        public virtual SteamVR_Action_Boolean Masturbate
        {
            get
            {
                return SteamVR_Actions.default_Masturbate;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Inventory
        {
            get
            {
                return SteamVR_Actions.default_Inventory;
            }
        }
        
        public virtual SteamVR_Action_Boolean Memories
        {
            get
            {
                return SteamVR_Actions.default_Memories;
            }
        }
        
        public virtual SteamVR_Action_Boolean Opportunities
        {
            get
            {
                return SteamVR_Actions.default_Opportunities;
            }
        }
        
        public virtual SteamVR_Action_Boolean Flash
        {
            get
            {
                return SteamVR_Actions.default_Flash;
            }
        }
        
        public virtual SteamVR_Action_Boolean GameMenu
        {
            get
            {
                return SteamVR_Actions.default_GameMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Combat
        {
            get
            {
                return SteamVR_Actions.default_Combat;
            }
        }
        
        public virtual SteamVR_Action_Boolean Crouch
        {
            get
            {
                return SteamVR_Actions.default_Crouch;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
