//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVRActionSet
    {
        
        public virtual SteamVRActionVector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVRActionBoolean Grab
        {
            get
            {
                return SteamVR_Actions.default_Grab;
            }
        }
        
        public virtual SteamVRActionPose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVRActionSkeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVRActionSkeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVRActionBoolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVRActionBoolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVRActionBoolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVRActionBoolean UI_Radial
        {
            get
            {
                return SteamVR_Actions.default_UI_Radial;
            }
        }
        
        public virtual SteamVRActionBoolean Self_Radial
        {
            get
            {
                return SteamVR_Actions.default_Self_Radial;
            }
        }
        
        public virtual SteamVRActionBoolean Pee
        {
            get
            {
                return SteamVR_Actions.default_Pee;
            }
        }
        
        public virtual SteamVRActionBoolean Masturbate
        {
            get
            {
                return SteamVR_Actions.default_Masturbate;
            }
        }
        
        public virtual SteamVRActionBoolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVRActionBoolean Inventory
        {
            get
            {
                return SteamVR_Actions.default_Inventory;
            }
        }
        
        public virtual SteamVRActionBoolean Memories
        {
            get
            {
                return SteamVR_Actions.default_Memories;
            }
        }
        
        public virtual SteamVRActionBoolean Opportunities
        {
            get
            {
                return SteamVR_Actions.default_Opportunities;
            }
        }
        
        public virtual SteamVRActionBoolean Flash
        {
            get
            {
                return SteamVR_Actions.default_Flash;
            }
        }
        
        public virtual SteamVRActionBoolean GameMenu
        {
            get
            {
                return SteamVR_Actions.default_GameMenu;
            }
        }
        
        public virtual SteamVRActionBoolean Combat
        {
            get
            {
                return SteamVR_Actions.default_Combat;
            }
        }
        
        public virtual SteamVRActionBoolean Crouch
        {
            get
            {
                return SteamVR_Actions.default_Crouch;
            }
        }
        
        public virtual SteamVRActionVibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
